### ISSUE TITLE
Add XML-tag to top of metadata, and set content-type to application/xml

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/django-digid-eherkenning#30]
The XML-tag is now missing from the metadata. This is required since this year.

Also, when opening the metadata. The browser interprets it as an HTML document, rendering it badly. Can we set the content type to application/xml (or whatever is needed) so it shows properly in the browser?

**Comment by sergei-maertens** [comment]
> Also, when opening the metadata. The browser interprets it as an HTML document, rendering it badly. Can we set the content type to application/xml (or whatever is needed) so it shows properly in the browser?

I suspect it's due to the missing `<?xml ... ?>` tag then, as we set the proper XML content type: https://github.com/maykinmedia/django-digid-eherkenning/blob/bad7a697c458af83766e3728e225dadd6892198b/digid_eherkenning/views/metadata.py#L46

Unless browsers require `application/xml`, but iirc `text/xml` is the correct one.
