### ISSUE TITLE
Make Sign assertions default True for DigiD

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/django-digid-eherkenning#51]
`Onderteken assertions` should be set to `True` by default to make sure `WantAssertionsSigned is set to `true` in the XML metadata. Can we make this the default?

**Comment by SilviaAmAm** [comment]
It looks like this was already the case since version 0.5: https://github.com/maykinmedia/django-digid-eherkenning/blob/master/CHANGELOG.rst#050-2022-10-31, https://github.com/maykinmedia/django-digid-eherkenning/blob/108170812aa1be8dbc74821a14aef5f67b6e49d5/digid_eherkenning/models/base.py#L62

@joeribekker Are there instances for which the wrong default was set?

**Comment by SilviaAmAm** [comment]
Spinning up a docker container with the current OF latest (ef49482f9cf98ca8c92f2c61b4f9f3702b2b6df8) has the checkbox already checked:
![Screenshot from 2023-12-28 10-48-52](https://github.com/maykinmedia/django-digid-eherkenning/assets/19154114/9e9f4e2e-f813-4bcf-aae8-f10258c3b750)
